version: '3.1'

services:

  postgres:
    container_name: postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: jpatryout
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5432:5432"
    restart: unless-stopped

  oracle:
    container_name: oracle
    image: wnameless/oracle-xe-11g-r2
    environment:
      ORACLE_ALLOW_REMOTE: "true"
    ports:
      - "1521:1521"
    restart: unless-stopped
