spring:
  datasource:
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:memory:myDb;create=true
    username: sa
    password: sa
  jpa:
    show-sql: true
    database: derby
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DerbyDialect
